spring:
  application:
    name: Ponto

  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

springdoc:
  default-consumes-media-type: application/json

  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha


ponto:
  security:
    secret: "secret-key"